version: "3"

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    container_name: novel_api
    ports: 
      - "8080:8080"
    volumes:
      - .:/home/app
      - /home/app/node_modules
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    expose:
      - 8080
